baseURL = "http://www.engines.org/"
languageCode = "en-us"
title = "Engines"


#################################### Plugins ##########################################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"


###################################### Navigation ######################################

# homepage section menu
# [[menu.main]]
# name = "Home"
# URL = "/"
# weight = 1
#
# [[menu.main]]
# name = "Apps"
# URL = "apps"
# weight = 2
#
# [[menu.main]]
# name = "Blog"
# URL = "blog"
# weight = 3
#
# [[menu.main]]
# name = "Contact"
# URL = "contact"
# weight = 5

# # footer menu
# [[menu.footer]]
# name = "Blog"
# URL = "blog"
# weight = 1
#
# [[menu.footer]]
# name = "Contact"
# URL = "contact"
# weight = 2

########################### meta ##########################
[params]
logo = "images/logo.png"
logo_width = "100px"
# Meta data
description = "Engines - Self-host a personal server"
author = "Lachlan Douglas"

########################### renderer ##########################
[markup.goldmark.renderer]
unsafe = true


# # currency
# currency = "$"
# # contact form action
# contact_form_action = "#" # contact form works with https://formspree.io
# # snipcart public api key
# snipcart_api = "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"
#
# # Preloader
# [params.preloader]
# enable = true
# preloader = "" # use .png , .svg or .gif format
#
# # Subscription
# [params.subscription]
# # mailchimp subsciption
# mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
# mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
# copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
# copyright
# copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
